<?php

namespace App;

/**
 * Represnets a connection to a SQLite database
 *
 * @author Kieran Knowles
 * @generated GitHub Copilot was used to assist in writing this code
 */
class DatabaseConnection
{
    private \PDO $pdo;

    public function __construct(string $file)
    {
        $this->pdo = new \PDO("sqlite:$file");
        // Throw exceptions on error
        $this->pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
    }

    /**
     * Run a SQL query and return the result
     * @param string $sql The SQL query to run
     * @param array<string, string|number|bool|null> $params The parameters to pass to the query
     * @return array The result of the query, as an array of associative arrays. Structure depends on the query
     */
    public function runSql(string $sql, array $params = []): array // @phpstan-ignore-line Type depends on query
    {
        $statement = $this->pdo->prepare($sql);
        $statement->execute($params);
        return $statement->fetchAll(\PDO::FETCH_ASSOC);
    }

    /**
     * Run an insert, update or delete query and return the number of rows affected
     * @param string $sql The SQL query to run
     * @param array<string, string|number|bool|null> $params The parameters to pass to the query
     * @return int The number of rows affected
     */
    public function runUpdateSql(string $sql, array $params = []): int
    {
        $statement = $this->pdo->prepare($sql);
        $statement->execute($params);
        return $statement->rowCount();
    }

    /**
     * Get the last ID generated by an INSERT query
     */
    public function getLastInsertId(): string
    {
        $id = $this->pdo->lastInsertId();
        if ($id === false) {
            throw new \Exception("Failed to get last insert ID, did you INSERT anything?");
        }
        return $id;
    }
}
